"""Tests for the Sports Event Calendar app.
Generated by Claude Opus 4.6.
All database access is mocked so tests run without PostgreSQL.
Run with:  pytest test_app.py -v
"""

from unittest.mock import MagicMock, patch

import pytest

from app import app, get_or_create_sport_id, get_or_create_team_id, get_or_create_venue_id


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

SAMPLE_EVENT = {
    "id": 1,
    "event_date": "2026-03-22",
    "event_time": "18:30:00",
    "sport": "Football",
    "home_team": "Salzburg",
    "away_team": "Sturm",
    "venue_name": "Red Bull Arena",
    "venue_city": "Salzburg",
    "venue_country": "Austria",
    "description": "League match",
}

VALID_PAYLOAD = {
    "event_date": "2026-03-22",
    "event_time": "18:30",
    "sport": "Football",
    "home_team": "Salzburg",
    "away_team": "Sturm",
    "venue_name": "Red Bull Arena",
    "venue_city": "Salzburg",
    "venue_country": "Austria",
    "description": "League match",
}


@pytest.fixture()
def client():
    """Flask test client with a mocked DB connection."""
    app.config["TESTING"] = True

    mock_conn = MagicMock()
    mock_cursor = MagicMock()
    mock_conn.cursor.return_value.__enter__ = MagicMock(return_value=mock_cursor)
    mock_conn.cursor.return_value.__exit__ = MagicMock(return_value=False)

    with patch("app.get_connection", return_value=mock_conn):
        with app.test_client() as c:
            yield c


# ---------------------------------------------------------------------------
# Helper-function unit tests
# ---------------------------------------------------------------------------


class TestGetOrCreateHelpers:
    """Unit tests for the get_or_create_* helpers."""

    def test_get_or_create_sport_id(self):
        cur = MagicMock()
        cur.fetchone.return_value = (7,)

        result = get_or_create_sport_id(cur, "Football")

        cur.execute.assert_called_once()
        sql = cur.execute.call_args[0][0]
        assert "INSERT INTO sports" in sql
        assert "RETURNING id" in sql
        assert cur.execute.call_args[0][1] == ("Football",)
        assert result == 7

    def test_get_or_create_team_id_with_country(self):
        cur = MagicMock()
        cur.fetchone.return_value = (3,)

        result = get_or_create_team_id(cur, "Salzburg", "AUT")

        assert cur.execute.call_args[0][1] == ("Salzburg", "AUT")
        assert result == 3

    def test_get_or_create_team_id_without_country(self):
        cur = MagicMock()
        cur.fetchone.return_value = (4,)

        result = get_or_create_team_id(cur, "Sturm")

        assert cur.execute.call_args[0][1] == ("Sturm", None)
        assert result == 4

    def test_get_or_create_venue_id_returns_id(self):
        cur = MagicMock()
        cur.fetchone.return_value = (2,)

        result = get_or_create_venue_id(cur, "Red Bull Arena", "Salzburg", "Austria")

        assert cur.execute.call_args[0][1] == ("Red Bull Arena", "Salzburg", "Austria")
        assert result == 2

    def test_get_or_create_venue_id_returns_none_when_no_name(self):
        cur = MagicMock()

        result = get_or_create_venue_id(cur)

        cur.execute.assert_not_called()
        assert result is None

    def test_get_or_create_venue_id_empty_string_name(self):
        cur = MagicMock()

        result = get_or_create_venue_id(cur, venue_name="")

        cur.execute.assert_not_called()
        assert result is None


# ---------------------------------------------------------------------------
# GET / (index page)
# ---------------------------------------------------------------------------


class TestIndexRoute:

    @patch("app.get_sports", return_value=["Football", "Ice Hockey"])
    @patch("app.fetch_events", return_value=[SAMPLE_EVENT])
    def test_index_renders_events(self, mock_fetch, mock_sports, client):
        resp = client.get("/")

        assert resp.status_code == 200
        html = resp.data.decode()
        assert "Salzburg" in html
        assert "Sturm" in html
        mock_fetch.assert_called_once_with(sport=None, event_date=None)

    @patch("app.get_sports", return_value=["Football", "Ice Hockey"])
    @patch("app.fetch_events", return_value=[])
    def test_index_shows_no_events_message(self, mock_fetch, mock_sports, client):
        resp = client.get("/")

        assert resp.status_code == 200
        assert "No events found" in resp.data.decode()

    @patch("app.get_sports", return_value=["Football"])
    @patch("app.fetch_events", return_value=[])
    def test_index_passes_sport_filter(self, mock_fetch, mock_sports, client):
        client.get("/?sport=Football")

        mock_fetch.assert_called_once_with(sport="Football", event_date=None)

    @patch("app.get_sports", return_value=["Football"])
    @patch("app.fetch_events", return_value=[])
    def test_index_passes_date_filter(self, mock_fetch, mock_sports, client):
        client.get("/?date=2026-03-22")

        mock_fetch.assert_called_once_with(sport=None, event_date="2026-03-22")

    @patch("app.get_sports", return_value=[])
    @patch("app.fetch_events", return_value=[])
    def test_index_shows_flash_message(self, mock_fetch, mock_sports, client):
        resp = client.get("/?message=Event+added")

        assert "Event added" in resp.data.decode()


# ---------------------------------------------------------------------------
# POST /events (form submission)
# ---------------------------------------------------------------------------


class TestFormSubmission:

    @patch("app.create_event", return_value=1)
    def test_form_creates_event_and_redirects(self, mock_create, client):
        resp = client.post("/events", data=VALID_PAYLOAD)

        assert resp.status_code == 302
        assert "message=Event+added" in resp.headers["Location"]
        mock_create.assert_called_once()

    def test_form_rejects_missing_required_fields(self, client):
        incomplete = {
            "event_date": "2026-03-22",
            "event_time": "",
            "sport": "Football",
            "home_team": "Salzburg",
            "away_team": "Sturm",
        }
        resp = client.post("/events", data=incomplete)

        assert resp.status_code == 302
        assert "Missing+required" in resp.headers["Location"]

    def test_form_rejects_completely_missing_field(self, client):
        """Field key absent from form data entirely."""
        incomplete = {
            "event_date": "2026-03-22",
            "sport": "Football",
            "home_team": "Salzburg",
            "away_team": "Sturm",
            # event_time is missing entirely
        }
        resp = client.post("/events", data=incomplete)

        assert resp.status_code == 302
        assert "Missing+required" in resp.headers["Location"]


# ---------------------------------------------------------------------------
# GET /api/events
# ---------------------------------------------------------------------------


class TestApiGetEvents:

    @patch("app.fetch_events", return_value=[SAMPLE_EVENT])
    def test_returns_all_events(self, mock_fetch, client):
        resp = client.get("/api/events")
        data = resp.get_json()

        assert resp.status_code == 200
        assert len(data) == 1
        assert data[0]["sport"] == "Football"
        mock_fetch.assert_called_once_with(sport=None, event_date=None)

    @patch("app.fetch_events", return_value=[])
    def test_returns_empty_list(self, mock_fetch, client):
        resp = client.get("/api/events")

        assert resp.status_code == 200
        assert resp.get_json() == []

    @patch("app.fetch_events", return_value=[SAMPLE_EVENT])
    def test_filters_by_sport(self, mock_fetch, client):
        client.get("/api/events?sport=Football")

        mock_fetch.assert_called_once_with(sport="Football", event_date=None)

    @patch("app.fetch_events", return_value=[SAMPLE_EVENT])
    def test_filters_by_date(self, mock_fetch, client):
        client.get("/api/events?date=2026-03-22")

        mock_fetch.assert_called_once_with(sport=None, event_date="2026-03-22")

    @patch("app.fetch_events", return_value=[SAMPLE_EVENT])
    def test_filters_by_sport_and_date(self, mock_fetch, client):
        client.get("/api/events?sport=Football&date=2026-03-22")

        mock_fetch.assert_called_once_with(sport="Football", event_date="2026-03-22")


# ---------------------------------------------------------------------------
# GET /api/events/<id>
# ---------------------------------------------------------------------------


class TestApiGetEventById:

    @patch("app.fetch_event_by_id", return_value=SAMPLE_EVENT)
    def test_returns_event(self, mock_fetch, client):
        resp = client.get("/api/events/1")
        data = resp.get_json()

        assert resp.status_code == 200
        assert data["id"] == 1
        assert data["home_team"] == "Salzburg"
        mock_fetch.assert_called_once_with(1)

    @patch("app.fetch_event_by_id", return_value=None)
    def test_returns_404_when_not_found(self, mock_fetch, client):
        resp = client.get("/api/events/999")

        assert resp.status_code == 404
        assert resp.get_json()["error"] == "Event not found"


# ---------------------------------------------------------------------------
# POST /api/events
# ---------------------------------------------------------------------------


class TestApiCreateEvent:

    @patch("app.create_event", return_value=42)
    def test_creates_event_returns_201(self, mock_create, client):
        resp = client.post(
            "/api/events",
            json=VALID_PAYLOAD,
        )
        data = resp.get_json()

        assert resp.status_code == 201
        assert data["id"] == 42
        mock_create.assert_called_once()

    def test_rejects_missing_fields(self, client):
        resp = client.post(
            "/api/events",
            json={"event_date": "2026-03-22"},
        )
        data = resp.get_json()

        assert resp.status_code == 400
        assert "Missing fields" in data["error"]
        assert "event_time" in data["error"]
        assert "sport" in data["error"]

    def test_rejects_empty_body(self, client):
        resp = client.post(
            "/api/events",
            json={},
        )

        assert resp.status_code == 400
        assert "Missing fields" in resp.get_json()["error"]

    def test_rejects_non_json_body(self, client):
        resp = client.post(
            "/api/events",
            data="not json",
            content_type="text/plain",
        )

        assert resp.status_code == 400

    @patch("app.create_event", return_value=1)
    def test_optional_fields_not_required(self, mock_create, client):
        """venue_name, venue_city, venue_country, description are optional."""
        minimal = {
            "event_date": "2026-03-22",
            "event_time": "18:30",
            "sport": "Football",
            "home_team": "Salzburg",
            "away_team": "Sturm",
        }
        resp = client.post("/api/events", json=minimal)

        assert resp.status_code == 201
        mock_create.assert_called_once()


# ---------------------------------------------------------------------------
# fetch_events query-building logic
# ---------------------------------------------------------------------------


class TestFetchEventsQuery:
    """Verify the dynamic WHERE-clause construction in fetch_events."""

    @patch("app.get_db")
    def test_no_filters_produces_no_where(self, mock_get_db):
        mock_cur = MagicMock()
        mock_cur.fetchall.return_value = []
        mock_get_db.return_value.cursor.return_value.__enter__ = MagicMock(
            return_value=mock_cur
        )
        mock_get_db.return_value.cursor.return_value.__exit__ = MagicMock(
            return_value=False
        )

        with app.app_context():
            from app import fetch_events
            fetch_events()

        executed_sql = mock_cur.execute.call_args[0][0]
        assert "WHERE" not in executed_sql
        assert "ORDER BY" in executed_sql

    @patch("app.get_db")
    def test_sport_filter_adds_where(self, mock_get_db):
        mock_cur = MagicMock()
        mock_cur.fetchall.return_value = []
        mock_get_db.return_value.cursor.return_value.__enter__ = MagicMock(
            return_value=mock_cur
        )
        mock_get_db.return_value.cursor.return_value.__exit__ = MagicMock(
            return_value=False
        )

        with app.app_context():
            from app import fetch_events
            fetch_events(sport="Football")

        executed_sql = mock_cur.execute.call_args[0][0]
        params = mock_cur.execute.call_args[0][1]
        assert "WHERE" in executed_sql
        assert "s.name = %s" in executed_sql
        assert params == ["Football"]

    @patch("app.get_db")
    def test_both_filters_combined_with_and(self, mock_get_db):
        mock_cur = MagicMock()
        mock_cur.fetchall.return_value = []
        mock_get_db.return_value.cursor.return_value.__enter__ = MagicMock(
            return_value=mock_cur
        )
        mock_get_db.return_value.cursor.return_value.__exit__ = MagicMock(
            return_value=False
        )

        with app.app_context():
            from app import fetch_events
            fetch_events(sport="Football", event_date="2026-03-22")

        executed_sql = mock_cur.execute.call_args[0][0]
        params = mock_cur.execute.call_args[0][1]
        assert "WHERE" in executed_sql
        assert "AND" in executed_sql
        assert params == ["Football", "2026-03-22"]
